#pragma once

#ifndef MISTY_PLUGIN_API_VERSION
#define MISTY_PLUGIN_API_VERSION "dev"
#endif

#ifndef MISTY_PLUGIN_BUILD_ID
#define MISTY_PLUGIN_BUILD_ID "dev"
#endif

#ifndef MISTY_PLUGIN_TRUST_PUBKEY_PEM
#define MISTY_PLUGIN_TRUST_PUBKEY_PEM ""
#endif

#ifndef MISTY_PLUGIN_USER_TRUST_DIR
#define MISTY_PLUGIN_USER_TRUST_DIR ""
#endif

#ifndef MISTY_REQUIRE_SIGNED_PLUGINS
#define MISTY_REQUIRE_SIGNED_PLUGINS 0
#endif
